semi: false
singleQuote: true
arrowParens: always
# This is no need, prettier can judge which parser to use
# overrides:
#   - files: '*.vue'
#     parser: vue

#   - files: '*.md'
#     parser: markdown
